export const SeederConfig = Object.freeze({
   NUMBER_OF_ADMINS: 1,
   NUMBER_OF_MANAGERS: 2,
   NUMBER_OF_CLIENTS: 100,
   NUMBER_OF_FAVORITE_BOOKS_PER_USER: 10,
   NUMBER_OF_AUTHORS: 20,
   NUMBER_OF_BOOKS: 100,
   NUMBER_OF_LOANS: 80,
});
